#!/usr/bin/env bash
# pings a ip 5 times
# displays 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}' if no arg passed
if [ $# -eq 0 ];
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}";
else
    ping -c 5 "$1";
fi

				
